# Generated by Django 5.2.5 on 2025-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_musician_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XLarge')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
