# Generated by Django 5.2.5 on 2025-08-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post_name', models.SlugField()),
                ('content', models.TextField(max_length=800)),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
