# Generated by Django 5.2.5 on 2025-08-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
