# Generated by Django 5.2.5 on 2025-08-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_name_post_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.SlugField(default=models.CharField(max_length=50)),
        ),
    ]
